-- Generated by scratchpad/gen-seed.js. Re-runnable: clears the org first.
delete from public.organizations where id = '00000000-0000-4000-8000-000000000001';

insert into public.organizations (id, name, avatar_url) values
  ('00000000-0000-4000-8000-000000000001', 'Bays Ranch', '/assets/avatar.png');

-- Three people share this screen, at the three permission levels the product
-- implies: the owner, the office manager who reviews logs, and a crew lead who
-- can only read. Switch User picks between them; every write is authorised
-- against the role, not against what the UI happens to show.
insert into public.members (id, org_id, display_name, role) values
  ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'Dana Reyes',  'admin'),
  ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', 'Marco Silva', 'manager'),
  ('00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001', 'Priya Nair',  'worker');

insert into public.employees (id, org_id, full_name, is_active) values
  ('00000000-0000-4000-8000-e00000000001', '00000000-0000-4000-8000-000000000001', 'Isaac Wang', true),
  ('00000000-0000-4000-8000-e00000000002', '00000000-0000-4000-8000-000000000001', 'Maya Patel', true),
  ('00000000-0000-4000-8000-e00000000003', '00000000-0000-4000-8000-000000000001', 'Liam Johnson', true),
  ('00000000-0000-4000-8000-e00000000004', '00000000-0000-4000-8000-000000000001', 'Sophia Lee', true),
  ('00000000-0000-4000-8000-e00000000005', '00000000-0000-4000-8000-000000000001', 'Ethan Kim', true),
  ('00000000-0000-4000-8000-e00000000006', '00000000-0000-4000-8000-000000000001', 'Olivia Martinez', true),
  ('00000000-0000-4000-8000-e00000000007', '00000000-0000-4000-8000-000000000001', 'Noah Brown', true),
  ('00000000-0000-4000-8000-e00000000008', '00000000-0000-4000-8000-000000000001', 'Emma Davis', true),
  ('00000000-0000-4000-8000-e00000000009', '00000000-0000-4000-8000-000000000001', 'James Wilson', true),
  ('00000000-0000-4000-8000-e00000000010', '00000000-0000-4000-8000-000000000001', 'Isabella Garcia', true),
  ('00000000-0000-4000-8000-e00000000011', '00000000-0000-4000-8000-000000000001', 'Benjamin Moore', true),
  ('00000000-0000-4000-8000-e00000000012', '00000000-0000-4000-8000-000000000001', 'Ava Thompson', true);

insert into public.activity_types (id, name) values
  ('00000000-0000-4000-8000-a00000000001', 'Spraying'),
  ('00000000-0000-4000-8000-a00000000002', 'Harvesting'),
  ('00000000-0000-4000-8000-a00000000003', 'Planting'),
  ('00000000-0000-4000-8000-a00000000004', 'Irrigation'),
  ('00000000-0000-4000-8000-a00000000005', 'Fertilizing'),
  ('00000000-0000-4000-8000-a00000000006', 'Weeding'),
  ('00000000-0000-4000-8000-a00000000007', 'Pruning'),
  ('00000000-0000-4000-8000-a00000000008', 'Monitoring'),
  ('00000000-0000-4000-8000-a00000000009', 'Soil Testing'),
  ('00000000-0000-4000-8000-a00000000010', 'Seeding'),
  ('00000000-0000-4000-8000-a00000000011', 'Pest Control');

insert into public.fields (id, org_id, name, map_plot) values
  ('00000000-0000-4000-8000-f00000000001', '00000000-0000-4000-8000-000000000001', 'FIELD A', '{"x":268,"y":134,"width":88,"height":52}'::jsonb),
  ('00000000-0000-4000-8000-f00000000002', '00000000-0000-4000-8000-000000000001', 'FIELD B', '{"x":52,"y":48,"width":96,"height":60}'::jsonb),
  ('00000000-0000-4000-8000-f00000000003', '00000000-0000-4000-8000-000000000001', 'FIELD C', '{"x":180,"y":40,"width":84,"height":56}'::jsonb),
  ('00000000-0000-4000-8000-f00000000004', '00000000-0000-4000-8000-000000000001', 'FIELD D', '{"x":420,"y":44,"width":110,"height":58}'::jsonb),
  ('00000000-0000-4000-8000-f00000000005', '00000000-0000-4000-8000-000000000001', 'FIELD E', '{"x":44,"y":150,"width":100,"height":54}'::jsonb),
  ('00000000-0000-4000-8000-f00000000006', '00000000-0000-4000-8000-000000000001', 'FIELD F', '{"x":168,"y":232,"width":90,"height":56}'::jsonb),
  ('00000000-0000-4000-8000-f00000000007', '00000000-0000-4000-8000-000000000001', 'FIELD G', '{"x":300,"y":236,"width":98,"height":52}'::jsonb),
  ('00000000-0000-4000-8000-f00000000008', '00000000-0000-4000-8000-000000000001', 'FIELD H', '{"x":440,"y":232,"width":96,"height":58}'::jsonb),
  ('00000000-0000-4000-8000-f00000000009', '00000000-0000-4000-8000-000000000001', 'FIELD I', '{"x":60,"y":260,"width":88,"height":50}'::jsonb),
  ('00000000-0000-4000-8000-f00000000010', '00000000-0000-4000-8000-000000000001', 'FIELD J', '{"x":384,"y":128,"width":104,"height":60}'::jsonb),
  ('00000000-0000-4000-8000-f00000000011', '00000000-0000-4000-8000-000000000001', 'FIELD K', '{"x":150,"y":132,"width":92,"height":54}'::jsonb);

-- Dates are relative to the day the seed runs so "This Month" and "Todays
-- Recordings" derive from the rows: four logs land in the current month (on or
-- before today), the other seven in the previous month.
with p as (
  select
    (date_trunc('month', current_date)::date
      + least(extract(day from current_date)::int - 1, 3)) as anchor,
    (date_trunc('month', current_date) - interval '1 month')::date + 4 as prev_month
),
v (id, employee_id, field_id, activity_type_id, this_month, day_offset, start_time, end_time, status) as (
  values
    ('00000000-0000-4000-8000-100000000001'::uuid, '00000000-0000-4000-8000-e00000000001'::uuid, '00000000-0000-4000-8000-f00000000001'::uuid, '00000000-0000-4000-8000-a00000000001'::uuid, true, 3, time '06:00', time '10:40', 'new'::public.log_status),
    ('00000000-0000-4000-8000-100000000002'::uuid, '00000000-0000-4000-8000-e00000000002'::uuid, '00000000-0000-4000-8000-f00000000002'::uuid, '00000000-0000-4000-8000-a00000000002'::uuid, true, 2, time '07:30', time '11:15', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000003'::uuid, '00000000-0000-4000-8000-e00000000003'::uuid, '00000000-0000-4000-8000-f00000000003'::uuid, '00000000-0000-4000-8000-a00000000003'::uuid, true, 1, time '08:00', time '12:00', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000004'::uuid, '00000000-0000-4000-8000-e00000000004'::uuid, '00000000-0000-4000-8000-f00000000004'::uuid, '00000000-0000-4000-8000-a00000000004'::uuid, true, 0, time '06:30', time '09:30', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000005'::uuid, '00000000-0000-4000-8000-e00000000005'::uuid, '00000000-0000-4000-8000-f00000000005'::uuid, '00000000-0000-4000-8000-a00000000005'::uuid, false, 0, time '05:45', time '09:00', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000006'::uuid, '00000000-0000-4000-8000-e00000000006'::uuid, '00000000-0000-4000-8000-f00000000006'::uuid, '00000000-0000-4000-8000-a00000000006'::uuid, false, 1, time '06:15', time '10:00', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000007'::uuid, '00000000-0000-4000-8000-e00000000007'::uuid, '00000000-0000-4000-8000-f00000000007'::uuid, '00000000-0000-4000-8000-a00000000007'::uuid, false, 2, time '07:00', time '11:30', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000008'::uuid, '00000000-0000-4000-8000-e00000000008'::uuid, '00000000-0000-4000-8000-f00000000008'::uuid, '00000000-0000-4000-8000-a00000000008'::uuid, false, 3, time '08:15', time '12:45', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000009'::uuid, '00000000-0000-4000-8000-e00000000009'::uuid, '00000000-0000-4000-8000-f00000000009'::uuid, '00000000-0000-4000-8000-a00000000009'::uuid, false, 4, time '06:00', time '09:00', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000010'::uuid, '00000000-0000-4000-8000-e00000000010'::uuid, '00000000-0000-4000-8000-f00000000010'::uuid, '00000000-0000-4000-8000-a00000000010'::uuid, false, 5, time '07:45', time '11:00', 'reviewed'::public.log_status),
    ('00000000-0000-4000-8000-100000000011'::uuid, '00000000-0000-4000-8000-e00000000011'::uuid, '00000000-0000-4000-8000-f00000000011'::uuid, '00000000-0000-4000-8000-a00000000011'::uuid, false, 6, time '06:30', time '10:30', 'reviewed'::public.log_status)
)
insert into public.activity_logs (id, org_id, employee_id, field_id, activity_type_id, started_at, ended_at, status, created_at)
select
  v.id, '00000000-0000-4000-8000-000000000001', v.employee_id, v.field_id, v.activity_type_id,
  (case when v.this_month then p.anchor - v.day_offset else p.prev_month + v.day_offset end + v.start_time)::timestamptz,
  (case when v.this_month then p.anchor - v.day_offset else p.prev_month + v.day_offset end + v.end_time)::timestamptz,
  v.status,
  now() + (v.day_offset || ' milliseconds')::interval
from p, v;

-- Five recordings are stamped today so "Todays Recordings" reads 5; the rest
-- were dictated at the end of the shift they describe. Confidences average
-- exactly 0.90.
with v (log_id, today, duration_seconds, transcript, transcription_confidence, waveform, map_pin) as (
  values
    ('00000000-0000-4000-8000-100000000001'::uuid, true, 34, '"Offline guided voice log created at 2026-04-08T22:01:01.711Z. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: I''m leaving first, I''m going to go home. Question (field_block): Where were you working (field, block, or area)? Answer: yes, in one part and then 130 and 200 yes, and 130 for uh 160 and no, this yes no, no, uhm no no I remember, uhm uhm uhm, no, I don''t remember anything.', 0.62, '{"amplitudes":[0.08696,0.30435,0.43478,0.54348,0.63043,0.54348,0.43478,0.30435,0.15217,0.13043,0.15217,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.1087,0.13043,0.13043,0.13043,0.13043,0.13043,0.08696,0.1087,0.17391,0.21739,0.30435,0.21739,0.43478,0.78261,0.6087,0.43478,0.32609,0.26087,0.17391,0.13043,0.1087,0.19565,0.30435,0.5,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,0.13043,1,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":55}'::jsonb, '{"x":303,"y":153}'::jsonb),
    ('00000000-0000-4000-8000-100000000002'::uuid, true, 41, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: harvesting. Question (field_block): Where were you working (field, block, or area)? Answer: field B, the north rows by the pump house. Question (notes): Anything else to record? Answer: Pulled about forty crates before the heat came up, left the last two rows for tomorrow', 0.95, '{"amplitudes":[0.10487,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.11907,0.17564,0.22048,0.19331,0.20875,0.22641,0.23827,0.22443,0.23197,0.17157,0.20627,0.20442,0.20232,0.27866,0.32436,0.38167,0.34461,0.48592,0.42478,0.39093,0.69244,0.81583,0.52989,0.45455,0.66082,0.46961,0.4879,0.43874,0.44664,0.25865,0.35561,0.32868,0.25704,0.20652,0.22258,0.36685,0.3188,0.32992,0.27742,0.30336,0.30768,0.18367,0.19158,0.11203,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.12426,0.20813,0.22048,0.30694,0.30793,0.44256,0.30015,0.29113,0.40143,0.38352,0.26482,0.30324,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":72}'::jsonb, '{"x":88,"y":70}'::jsonb),
    ('00000000-0000-4000-8000-100000000003'::uuid, true, 29, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: planting. Question (field_block): Where were you working (field, block, or area)? Answer: field C, blocks one and two. Question (notes): Anything else to record? Answer: Transplanted the tomato starts on the west half, drip tape is down but not connected yet', 0.93, '{"amplitudes":[0.13365,0.1334,0.19046,0.20195,0.20776,0.23518,0.16749,0.25865,0.19096,0.19615,0.19503,0.16366,0.13241,0.11191,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.10845,0.15156,0.16193,0.22394,0.27223,0.32288,0.3267,0.49086,0.5378,0.45245,0.56349,0.50506,0.4685,0.52112,0.63661,0.40786,0.33819,0.49135,0.44355,0.32238,0.29422,0.42058,0.3335,0.27952,0.32868,0.34054,0.44812,0.2789,0.4496,0.37278,0.33683,0.38735,0.29212,0.4538,0.25778,0.24642,0.32411,0.2689,0.21579,0.16811,0.11672,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":64}'::jsonb, '{"x":214,"y":62}'::jsonb),
    ('00000000-0000-4000-8000-100000000004'::uuid, true, 26, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: irrigating. Question (field_block): Where were you working (field, block, or area)? Answer: field D. Question (notes): Anything else to record? Answer: Ran the center pivot for three hours, pressure was low on the east span so I flagged it for maintenance', 0.91, '{"amplitudes":[0.29583,0.32337,0.38303,0.5084,0.60981,0.7437,0.64773,0.66354,0.45825,0.38525,0.46974,0.37599,0.3918,0.36796,0.25185,0.33794,0.29718,0.34128,0.29163,0.2542,0.3897,0.323,0.25519,0.28767,0.21999,0.20072,0.19664,0.19763,0.11598,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.10227,0.16057,0.18454,0.23456,0.29286,0.4879,0.31806,0.34807,0.52693,0.35128,0.3288,0.36092,0.5105,0.51322,0.44368,0.29088,0.35203,0.28211,0.48555,0.3393,0.38723,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":58}'::jsonb, '{"x":468,"y":66}'::jsonb),
    ('00000000-0000-4000-8000-100000000005'::uuid, true, 38, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: fertilizing. Question (field_block): Where were you working (field, block, or area)? Answer: field E, whole block. Question (notes): Anything else to record? Answer: Side-dressed with urea at the usual rate, about a hundred and twenty pounds per acre, spreader calibrated this morning', 0.94, '{"amplitudes":[0.30472,0.30669,0.2831,0.15329,0.15156,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.13538,0.13673,0.21122,0.19862,0.27754,0.23641,0.30608,0.25556,0.26742,0.18392,0.17058,0.15254,0.20677,0.18454,0.198,0.29533,0.29138,0.28076,0.57695,0.52532,0.65514,0.69862,0.67885,0.53125,0.59746,0.61882,0.36166,0.46628,0.51865,0.47159,0.29533,0.30101,0.22628,0.29385,0.20245,0.26408,0.29076,0.23184,0.29274,0.32152,0.2936,0.36265,0.34684,0.23654,0.20949,0.16218,0.10511,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.11327,0.18207,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":70}'::jsonb, '{"x":82,"y":170}'::jsonb),
    ('00000000-0000-4000-8000-100000000006'::uuid, false, 31, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: weeding. Question (field_block): Where were you working (field, block, or area)? Answer: field F, rows ten through twenty-two. Question (notes): Anything else to record? Answer: Hand weeded the pepper rows, bindweed is coming back along the fence line', 0.92, '{"amplitudes":[0.37191,0.43639,0.42712,0.25321,0.18441,0.18824,0.1644,0.15057,0.13303,0.18664,0.16663,0.18626,0.18219,0.29731,0.30719,0.28953,0.21319,0.1623,0.16934,0.11401,0.08881,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.14056,0.20331,0.20047,0.23555,0.25556,0.45393,0.43775,0.41712,0.42354,0.45813,0.25074,0.39748,0.26803,0.23678,0.35511,0.36401,0.29051,0.45541,0.49704,0.42465,0.43293,0.59042,0.74654,0.52915,0.41391,0.78236,0.58325,0.42008,0.42095,0.59338,0.52186,0.36178,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":61}'::jsonb, '{"x":203,"y":254}'::jsonb),
    ('00000000-0000-4000-8000-100000000007'::uuid, false, 45, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: pruning. Question (field_block): Where were you working (field, block, or area)? Answer: field G, the orchard block. Question (notes): Anything else to record? Answer: Finished the summer prune on the first eight rows, cuttings are stacked at the end of row four', 0.9, '{"amplitudes":[0.15378,0.11858,0.12253,0.09116,0.08696,0.08696,0.08696,0.08696,0.09165,0.12129,0.16984,0.25,0.24728,0.31398,0.47567,0.35104,0.56843,0.47962,0.64056,0.70924,0.60363,0.60833,0.71665,0.67688,0.40897,0.33214,0.53854,0.30151,0.42367,0.31695,0.29039,0.22838,0.21332,0.20912,0.21208,0.17959,0.22814,0.22937,0.22875,0.2164,0.18602,0.18787,0.24395,0.23691,0.15501,0.15415,0.13612,0.12179,0.1129,0.09387,0.0893,0.08955,0.09956,0.12364,0.14452,0.20702,0.30398,0.25062,0.28866,0.37772,0.36623,0.60511,0.52619,0.57263,0.79224,0.65415,0.47468,0.59449,0.68256,0.44837,0.49741,0.48567,0.2999,0.29508,0.25716,0.24358,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":76}'::jsonb, '{"x":340,"y":256}'::jsonb),
    ('00000000-0000-4000-8000-100000000008'::uuid, false, 24, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: scouting. Question (field_block): Where were you working (field, block, or area)? Answer: field H. Question (notes): Anything else to record? Answer: Checked the traps, aphid counts are up on the south edge, no sign of mites yet', 0.96, '{"amplitudes":[0.26754,0.39242,0.27532,0.29002,0.21344,0.2169,0.17033,0.10536,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.11178,0.17465,0.23715,0.27804,0.26198,0.29928,0.57547,0.44219,0.50259,0.59412,0.58671,0.37562,0.42873,0.59832,0.34869,0.56732,0.36228,0.28928,0.40613,0.28014,0.30978,0.36969,0.24704,0.37994,0.28347,0.39847,0.4207,0.30361,0.26198,0.25506,0.3225,0.25161,0.22542,0.14167,0.12241,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":53}'::jsonb, '{"x":480,"y":255}'::jsonb),
    ('00000000-0000-4000-8000-100000000009'::uuid, false, 33, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: soil work. Question (field_block): Where were you working (field, block, or area)? Answer: field I, sampling grid points one through twelve. Question (notes): Anything else to record? Answer: Pulled twelve cores at six inches, bagged and labeled, they are in the cooler in the shop', 0.93, '{"amplitudes":[0.44281,0.36178,0.36154,0.23073,0.17997,0.15835,0.09486,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.12068,0.16131,0.16897,0.27199,0.22567,0.3246,0.21999,0.26075,0.19331,0.17947,0.22159,0.17404,0.18664,0.22048,0.34301,0.27952,0.4706,0.55398,0.54817,0.70875,0.5373,0.75753,0.61042,0.42416,0.54298,0.58461,0.46603,0.38303,0.32633,0.42169,0.42391,0.2605,0.44466,0.40217,0.36796,0.34202,0.33819,0.31411,0.43651,0.31003,0.23036,0.26692,0.16749,0.10808,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.12302,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":66}'::jsonb, '{"x":96,"y":280}'::jsonb),
    ('00000000-0000-4000-8000-100000000010'::uuid, false, 36, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: planting. Question (field_block): Where were you working (field, block, or area)? Answer: field J, east half. Question (notes): Anything else to record? Answer: Direct seeded the cover crop mix, seeder ran clean, about six acres done', 0.92, '{"amplitudes":[0.29583,0.20751,0.24555,0.24172,0.25803,0.32127,0.22875,0.30509,0.32955,0.29595,0.31608,0.21616,0.19578,0.20776,0.17441,0.12142,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.10931,0.16576,0.18207,0.18083,0.21171,0.31077,0.30805,0.18602,0.21467,0.26371,0.2353,0.17663,0.15588,0.1392,0.14748,0.19936,0.16181,0.22443,0.28693,0.3414,0.49531,0.44343,0.40057,0.38735,0.62574,0.60956,0.67391,0.70665,0.3587,0.45294,0.47097,0.3461,0.38278,0.47616,0.31028,0.39834,0.27372,0.28557,0.37204,0.49839,0.58362,0.37957,0.56645,0.59313,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":69}'::jsonb, '{"x":428,"y":152}'::jsonb),
    ('00000000-0000-4000-8000-100000000011'::uuid, false, 40, 'Offline guided voice log. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: spraying. Question (field_block): Where were you working (field, block, or area)? Answer: field K, rows one through thirty. Question (notes): Anything else to record? Answer: Applied spinosad for thrips, wind was calm, sprayer rinsed and parked', 0.92, '{"amplitudes":[0.2789,0.2106,0.22542,0.17218,0.10128,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.10968,0.1539,0.19219,0.27174,0.27705,0.3708,0.42824,0.63266,0.65736,0.65044,0.65662,0.42292,0.3687,0.41811,0.34177,0.32498,0.38118,0.29039,0.29755,0.28594,0.47493,0.38896,0.49592,0.49444,0.50865,0.40501,0.3934,0.385,0.23036,0.16625,0.15217,0.10079,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.09079,0.14785,0.22221,0.3246,0.28866,0.43046,0.30904,0.32041,0.52075,0.52421,0.51272,0.44022,0.53199,0.45813,0.40637,0.44269,0.43034,0.49247,0.47221,0.33152,0.45615,0.3834,0.39625,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696,0.08696],"voiced_bars":74}'::jsonb, '{"x":186,"y":153}'::jsonb)
)
insert into public.recordings (log_id, duration_seconds, recorded_at, transcript, transcription_confidence, waveform, map_pin)
select
  v.log_id, v.duration_seconds,
  case when v.today then (current_date + l.ended_at::time)::timestamptz else l.ended_at end,
  v.transcript, v.transcription_confidence, v.waveform, v.map_pin
from v
join public.activity_logs l on l.id = v.log_id;

-- ---------------------------------------------------------------------------
-- What the crew actually said, and what the extractor made of it.
--
-- Applied as an update rather than inline above so the waveform arrays — which
-- are generated from real audio — stay where they are and this stays readable.
--
-- The transcripts are the demo. A compliance manager opening a log reads these
-- words before anything else, and until they were written the most important
-- content in the product was the ingestion harness's own scaffolding
-- ("Question (activity_type): What type of activity was this...") — which is
-- not a thing any farm worker has ever said.
--
-- Three details are deliberate:
--
--   * Isaac Wang's is degraded, with [inaudible] where the wind took the words.
--     That is why his transcription confidence is 0.62, why the extractor got
--     no product or rate out of it, and why his log is the one missing its
--     compliance record. One cause, visible in four places.
--   * Ethan Kim says he ran out before the far end and never measured the area,
--     which is exactly why his record is filed but incomplete.
--   * Two logs are in Spanish, because most people doing crop work in the US
--     speak it. `transcript` stays in the language it was spoken — that is the
--     record an inspector is entitled to — and `transcript_en` carries the
--     English for whoever is reading the dashboard.
-- ---------------------------------------------------------------------------
update public.recordings r
set transcript = v.spoken, transcript_en = v.english, language = v.lang,
    extracted_fields = v.extracted::jsonb
from (values
  ('00000000-0000-4000-8000-100000000001'::uuid,
   'Okay this is Isaac, uh, I''m on Field A, we just finished the — [inaudible] — the spray on the north half. Wind picked up around [inaudible] so we stopped early. I''ll have to check the jug for the — [inaudible] — I didn''t write the rate down.',
   null, 'en',
   '{"activityType":{"value":"Spraying","confidence":0.88},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD A","confidence":0.93},"weather":{"value":"Wind rising, speed not stated","confidence":0.42}}'),
  ('00000000-0000-4000-8000-100000000002'::uuid,
   'Maya here. Finished picking Field B, the whole block. Started half seven, wrapped up around quarter past eleven. Good yield on the east rows, the west side is still a week out I''d say.',
   null, 'en',
   '{"activityType":{"value":"Harvesting","confidence":0.97},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD B","confidence":0.99},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000003'::uuid,
   'Liam, Field C. Got the transplants in across the whole block today, eight in the morning through noon. Soil was still a bit wet from Tuesday so we went slower than planned but they''re all in the ground.',
   null, 'en',
   '{"activityType":{"value":"Planting","confidence":0.96},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD C","confidence":0.98},"weather":{"value":"Soil wet from recent rain","confidence":0.71}}'),
  ('00000000-0000-4000-8000-100000000004'::uuid,
   'Sophia. Ran irrigation on Field D this morning, six thirty to about nine thirty. Line four had a slow emitter near the south corner, I flagged it, someone should look at it before the next set.',
   null, 'en',
   '{"activityType":{"value":"Irrigation","confidence":0.95},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD D","confidence":0.97},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000005'::uuid,
   'Ethan, Field E. Side-dressed with urea at the usual rate, about a hundred and twenty pounds per acre. Spreader was calibrated this morning. I didn''t measure how much of the block we covered, we ran out before the far end.',
   null, 'en',
   '{"activityType":{"value":"Fertilizing","confidence":0.96},"product":{"value":"Urea 46-0-0","confidence":0.93},"rate":{"value":"120 lb/acre","confidence":0.9},"field":{"value":"FIELD E","confidence":0.98},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000006'::uuid,
   'Soy Olivia. Estuve desyerbando el Campo F toda la mañana, desde las seis y cuarto hasta las diez. La hierba está peor en la orilla del canal, por allá hay que volver la próxima semana.',
   'This is Olivia. I was weeding Field F all morning, from six fifteen until ten. The weeds are worst along the edge of the ditch — we need to go back there next week.', 'es',
   '{"activityType":{"value":"Weeding","confidence":0.94},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD F","confidence":0.96},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000007'::uuid,
   'Noah, Field G. Pruning all morning, seven to half eleven. Took out the dead wood on the older rows. There''s some canker on maybe six or seven trees at the top of the block, worth having someone look.',
   null, 'en',
   '{"activityType":{"value":"Pruning","confidence":0.95},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD G","confidence":0.97},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000008'::uuid,
   'Emma. Scouting Field H, eight fifteen through to about quarter to one. Counted aphids on the lower leaves, maybe five or six per plant on the south end, nothing on the north. Not at threshold yet but I''d check again in three days.',
   null, 'en',
   '{"activityType":{"value":"Monitoring","confidence":0.97},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD H","confidence":0.98},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000009'::uuid,
   'James Wilson, soil sampling on Field I. Six to nine. Pulled cores from twelve spots across the block, bagged and labelled them. They''re in the shop fridge ready to go to the lab Monday.',
   null, 'en',
   '{"activityType":{"value":"Soil Testing","confidence":0.96},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD I","confidence":0.98},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000010'::uuid,
   'Habla Isabella. Terminé de sembrar el Campo J, empecé a las ocho menos cuarto y acabé como a las once. La sembradora se atascó dos veces en la parte de arriba donde la tierra está más dura.',
   'This is Isabella. I finished seeding Field J — I started at quarter to eight and finished around eleven. The seeder jammed twice at the top end where the ground is harder.', 'es',
   '{"activityType":{"value":"Seeding","confidence":0.92},"product":{"value":null,"confidence":null},"rate":{"value":null,"confidence":null},"field":{"value":"FIELD J","confidence":0.95},"weather":{"value":null,"confidence":null}}'),
  ('00000000-0000-4000-8000-100000000011'::uuid,
   'Benjamin, Field K. Pest control pass across eighteen acres. Ran Spinosad at half a gallon an acre and sulfur at five pounds an acre in the same tank. Wind was light, about three, temperature around seventy. Started six thirty, off by half ten.',
   null, 'en',
   '{"activityType":{"value":"Pest Control","confidence":0.98},"product":{"value":"Spinosad 480SC, Sulfur DF","confidence":0.94},"rate":{"value":"0.5 gal/acre, 5 lb/acre","confidence":0.91},"field":{"value":"FIELD K","confidence":0.99},"weather":{"value":"Wind 3 mph, 70 °F","confidence":0.89}}')
) as v(log_id, spoken, english, lang, extracted)
where r.log_id = v.log_id;

-- Starter tags for "Add Tag". A small vocabulary rather than none, so the
-- picker's fast path (choose an existing tag) is the one you meet first; new
-- names typed into the picker are created alongside these.
insert into public.tags (org_id, name) values
  ('00000000-0000-4000-8000-000000000001', 'Follow up'),
  ('00000000-0000-4000-8000-000000000001', 'Chemical applied'),
  ('00000000-0000-4000-8000-000000000001', 'Equipment issue'),
  ('00000000-0000-4000-8000-000000000001', 'Weather delay'),
  ('00000000-0000-4000-8000-000000000001', 'Verified')
on conflict (org_id, name) do nothing;

-- ---------------------------------------------------------------------------
-- The product register, and what was actually applied.
--
-- Each application matches what its log's transcript says, so the compliance
-- record and the worker's own words agree — including where they fall short.
-- The three states the Audit Manager exists to tell apart are all present:
--
--   log ...0011  Pest Control   two products, area and conditions  -> complete
--   log ...0005  Fertilizing    rate but no treated area           -> incomplete
--   log ...0001  Spraying       nothing at all                     -> missing
--
-- The last is not an oversight in the seed. That log's recording is the
-- 0.62-confidence one whose transcript came back as "I'm leaving first, I'm
-- going to go home" — a voice log that yielded neither an activity nor a
-- product should not have produced a record, and finding it is the job.
-- ---------------------------------------------------------------------------
insert into public.products (id, org_id, name, kind, epa_registration, active_ingredient, rate_unit, rei_hours, phi_days) values
  ('00000000-0000-4000-8000-b00000000001', '00000000-0000-4000-8000-000000000001', 'Spinosad 480SC',           'chemical',   '62719-291', 'Spinosad',          'gal/acre', 4,    7),
  ('00000000-0000-4000-8000-b00000000002', '00000000-0000-4000-8000-000000000001', 'Sulfur DF',                'chemical',   '70051-75',  'Sulfur',            'lb/acre',  24,   0),
  ('00000000-0000-4000-8000-b00000000003', '00000000-0000-4000-8000-000000000001', 'Glyphosate 41%',           'chemical',   '524-537',   'Glyphosate',        'gal/acre', 12,   14),
  ('00000000-0000-4000-8000-b00000000004', '00000000-0000-4000-8000-000000000001', 'Urea 46-0-0',              'fertilizer', null,        'Nitrogen (urea)',   'lb/acre',  null, null),
  ('00000000-0000-4000-8000-b00000000005', '00000000-0000-4000-8000-000000000001', 'Calcium Nitrate 15.5-0-0', 'fertilizer', null,        'Nitrogen, Calcium', 'lb/acre',  null, null),
  ('00000000-0000-4000-8000-b00000000006', '00000000-0000-4000-8000-000000000001', 'Compost, Class A',         'amendment',  null,        'Organic matter',    'ton/acre', null, null)
on conflict (id) do nothing;

insert into public.applications (log_id, product_id, rate, area_acres, wind_speed_mph, air_temp_f) values
  -- "about a hundred and twenty pounds per acre" — the transcript gives the rate
  -- but never the treated area, so the record exists and is incomplete.
  ('00000000-0000-4000-8000-100000000005', '00000000-0000-4000-8000-b00000000004', 120.000, null,  null, null),
  ('00000000-0000-4000-8000-100000000011', '00000000-0000-4000-8000-b00000000001', 0.500,   18.00, 3.5,  74.0),
  ('00000000-0000-4000-8000-100000000011', '00000000-0000-4000-8000-b00000000002', 5.000,   18.00, 3.5,  74.0)
on conflict (log_id, product_id) do nothing;

-- ---------------------------------------------------------------------------
-- A short starting history.
--
-- Inserted like any other event — through the trigger, which assigns the
-- sequence and the digest — so the seeded chain verifies rather than being a
-- special case the verification has to excuse. Without it the Audit Manager's
-- change history is empty on a fresh database, which shows the empty state
-- rather than the feature.
-- ---------------------------------------------------------------------------
with m as (
  select id, org_id, display_name, role from public.members order by role, display_name
),
admin as (select * from m where role = 'admin' limit 1),
mgr   as (select * from m where role = 'manager' limit 1),
-- Each event names the row it is actually about. An event that says
-- "Glyphosate" against a record holding Urea is worse than no seed at all: the
-- first thing anyone does with a history panel is check it against the record
-- beside it.
picks as (
  select
    (select id from public.products where name ilike 'Glyphosate%' limit 1) as glyphosate,
    a.id          as first_app,
    a.rate        as first_rate,
    p.name        as first_product,
    p.rate_unit   as first_unit,
    a.log_id      as first_app_log,
    (select id from public.recordings where log_id = a.log_id limit 1) as first_app_rec
  from public.applications a
  join public.products p on p.id = a.product_id
  order by a.created_at
  limit 1
)
insert into public.audit_events
  (org_id, actor_id, actor_label, action, entity_type, entity_id, summary, changes, created_at)
select * from (
  values
    ((select org_id from admin), (select id from admin), (select display_name from admin),
     'create'::public.audit_action, 'product', (select glyphosate from picks),
     'Added Glyphosate 41% to the product register',
     '{"Kind":{"from":null,"to":"chemical"},"Re-entry interval (hours)":{"from":null,"to":12}}'::jsonb,
     now() - interval '38 days'),
    ((select org_id from mgr), (select id from mgr), (select display_name from mgr),
     'create'::public.audit_action, 'application', (select first_app from picks),
     'Filed ' || (select first_product from picks) || ' at ' ||
       trim(trailing '.' from trim(trailing '0' from (select first_rate from picks)::text)) ||
       ' ' || (select first_unit from picks),
     jsonb_build_object('Rate', jsonb_build_object('from', null, 'to', (select first_rate from picks))),
     now() - interval '12 days'),
    ((select org_id from mgr), (select id from mgr), (select display_name from mgr),
     'update'::public.audit_action, 'recording', (select first_app_rec from picks),
     'Corrected a transcript',
     '{"Transcript":{"from":"side dressed with urea","to":"Side-dressed with urea"}}'::jsonb,
     now() - interval '11 days'),
    -- `actor_id` null is the ingestion pipeline rather than a person, and the
    -- trail says so in words rather than leaving a blank.
    ((select org_id from admin), null, 'Automated ingestion',
     'create'::public.audit_action, 'log', (select first_app_log from picks),
     'Created a log from a voice recording',
     '{"Status":{"from":null,"to":"new"}}'::jsonb,
     now() - interval '9 days')
) as v(org_id, actor_id, actor_label, action, entity_type, entity_id, summary, changes, created_at);


-- ---------------------------------------------------------------------------
-- The demo's clock.
--
-- Two of the seeded logs are re-dated relative to `now()` so the restricted
-- entry story is live whenever this is loaded rather than only on the day it
-- was written:
--
--   * Benjamin's pest-control pass on FIELD K ran this morning. Sulfur DF
--     carries a 24-hour re-entry interval, so the block is closed for the rest
--     of today — the safety item at the top of the triage queue.
--   * Liam's pre-plant burndown on FIELD C ran yesterday evening. Glyphosate's
--     12-hour interval has since elapsed, so that block reads as clear. Having
--     one of each is the point: a dashboard where every field is red teaches
--     people to ignore red.
--
-- The burndown is deliberately filed without an acreage — a real application
-- nobody measured — so the Pesticide Use Report has something to exclude and a
-- reason to say so at the foot of the file.
-- ---------------------------------------------------------------------------
update public.activity_logs
set started_at = date_trunc('hour', now()) - interval '4 hours',
    ended_at   = date_trunc('hour', now()) - interval '2 hours'
where id = '00000000-0000-4000-8000-100000000011';

update public.activity_logs
set started_at = date_trunc('hour', now()) - interval '22 hours',
    ended_at   = date_trunc('hour', now()) - interval '19 hours'
where id = '00000000-0000-4000-8000-100000000003';

insert into public.applications (log_id, product_id, rate, area_acres, wind_speed_mph, air_temp_f)
select '00000000-0000-4000-8000-100000000003', id, 1.5, null, 4.0, 66
from public.products where name ilike 'Glyphosate%'
on conflict (log_id, product_id) do update set area_acres = null;
